version: '3'

services:
  server:
    build: ./server
    container_name: server
    environment:
      - TZ=America/Montreal
    ports:
      - "80:80"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    environment:
      - TZ=America/Montreal
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./backend/app:/usr/src/app

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - TZ=America/Montreal
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public